mongo-url = "mongodb://root:secret@mongodb:27017"

change-stream-namespaces = [""]

elasticsearch-urls = ["http://elasticsearch:9200"]

elasticsearch-max-conns = 1

elasticsearch-max-seconds = 1

elasticsearch-max-docs = 1

verbose = true

enable-http-server = true